[uwsgi]
uid = uwsgi
gid = uwsgi
pidfile = /tmp/uwsgi.pid
emperor = /etc/uwsgi.d
stats = /tmp/stats.sock
chmod-socket = 660
emperor-tyrant = true
cap = setgid,setuid
plugins-dir = /usr/lib64/uwsgi
socket = :8081
plugins = python36,http,router_uwsgi,router_http
wsgi-file = test.py
master = true
